application: fumoufeed
version: 1
runtime: python27
api_version: 1
threadsafe: true


libraries:
- name: django
  version: latest
- name: ssl
  version: latest
- name: lxml
  version: latest

builtins:
- django_wsgi: on
- deferred: on
- remote_api: on

handlers:
- url: /.*
  script: fumoufeed.conf.wsgi.application

env_variables:
  DJANGO_SETTINGS_MODULE: 'fumoufeed.conf.settings'

skip_files:
- .*\.DS_Store
- \.git/*
- .*/local_settings.pyc?$
- .*\.pyc
- .*\.rb
- .*\.sass
- .*\.scss
- \.svn/*
- \.svn\-base
